# Generated by Django 4.1.3 on 2022-11-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertype',
            old_name='model',
            new_name='type',
        ),
    ]
